--[[ AUTOGENERATED - DO NOT MODIFY]]
--[[ See license.txt for license and copyright information ]]
select(2, ...).SetupGlobalFacade()

GuideInfos = {
	{
		description = "60-61 Hellfire Peninsula",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H60",
		rank = 201,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "60-61 Hellfire Peninsula",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A60",
		rank = 202,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "61-63 Zangarmarsh",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H61",
		rank = 203,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "61-63 Zangarmarsh",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A61",
		rank = 204,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "63-65 Terokkar Forest",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H63",
		rank = 205,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "63-65 Terokkar Forest",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A63",
		rank = 206,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "65-67 Nagrand",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H65",
		rank = 207,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "65-67 Nagrand",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A65",
		rank = 208,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "67-68 Blade's Edge Mountains",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H67",
		rank = 209,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "67-68 Blade's Edge Mountains",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A67",
		rank = 210,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "68-69 Netherstorm",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H68",
		rank = 211,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "68-69 Netherstorm",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A68",
		rank = 212,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "69-70 Shadowmoon Valley",
		faction = "Horde",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "H69",
		rank = 213,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "69-70 Shadowmoon Valley",
		faction = "Alliance",
		era = false,
		tbc = true,
		moduleID = "TBC",
		guideID = "A69",
		rank = 214,
		group = "Leveling Guides (60-70)",
		bookmarks = true
	},
	{
		description = "55-60 Death Knight",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H55",
		rank = 301,
		bookmarks = true
	},
	{
		description = "55-60 Death Knight",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A55",
		rank = 302,
		bookmarks = true
	},
	{
		description = "70-72 Borean Tundra",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Starter",
		guideID = "A70A",
		rank = 303,
		bookmarks = true
	},
	{
		description = "70-72 Howling Fjord",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Starter",
		guideID = "A70B",
		rank = 304,
		bookmarks = true
	},
	{
		description = "70-72 Borean Tundra",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Starter",
		guideID = "H70A",
		rank = 305,
		bookmarks = true
	},
	{
		description = "70-72 Howling Fjord",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Starter",
		guideID = "H70B",
		rank = 306,
		bookmarks = true
	},
	{
		description = "72-74 Dragonblight",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H72",
		rank = 307,
		bookmarks = true
	},
	{
		description = "72-74 Dragonblight",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A72",
		rank = 308,
		bookmarks = true
	},
	{
		description = "74-75 Grizzly Hills",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H74",
		rank = 309,
		bookmarks = true
	},
	{
		description = "74-75 Grizzly Hills",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A74",
		rank = 310,
		bookmarks = true
	},
	{
		description = "75-77 Zul'Drak",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H75",
		rank = 311,
		bookmarks = true
	},
	{
		description = "75-77 Zul'Drak",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A75",
		rank = 312,
		bookmarks = true
	},
	{
		description = "77-78 Sholazar Basin",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H77",
		rank = 313,
		bookmarks = true
	},
	{
		description = "77-78 Sholazar Basin",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A77",
		rank = 314,
		bookmarks = true
	},
	{
		description = "78-79 Storm Peaks",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H78",
		rank = 315,
		bookmarks = true
	},
	{
		description = "78-79 Storm Peaks",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A78",
		rank = 316,
		bookmarks = true
	},
	{
		description = "79-80 Icecrown",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "H79",
		rank = 317,
		bookmarks = true
	},
	{
		description = "79-80 Icecrown",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "A79",
		rank = 318,
		bookmarks = true
	},
	{
		description = "Borean Tundra (3 Dailies)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWBT",
		rank = 319,
		group = "Daily Quest Guides"
	},
	{
		description = "Borean Tundra (3 Dailies)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWBT",
		rank = 320,
		group = "Daily Quest Guides"
	},
	{
		description = "Howling Fjord (1 Daily)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWHF",
		rank = 321,
		group = "Daily Quest Guides"
	},
	{
		description = "Howling Fjord (1 Daily)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWHF",
		rank = 322,
		group = "Daily Quest Guides"
	},
	{
		description = "Dragon Blight (2 Dailies)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWDB",
		rank = 323,
		group = "Daily Quest Guides"
	},
	{
		description = "Dragon Blight (2 Dailies)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWDB",
		rank = 324,
		group = "Daily Quest Guides"
	},
	{
		description = "Grizzly Hills (8 PvP Dailies)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWGH",
		rank = 325,
		group = "Daily Quest Guides"
	},
	{
		description = "Grizzly Hills (8 PvP Dailies)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWGH",
		rank = 326,
		group = "Daily Quest Guides"
	},
	{
		description = "Zul'Drak (Troll Patrol)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWZD",
		rank = 327,
		group = "Daily Quest Guides"
	},
	{
		description = "Zul'Drak (Troll Patrol)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWZD",
		rank = 328,
		group = "Daily Quest Guides"
	},
	{
		description = "Sholazar Basin (Oracles Or Frenzyheart)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWSB",
		rank = 329,
		group = "Daily Quest Guides"
	},
	{
		description = "Sholazar Basin (Oracles Or Frenzyheart)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWSB",
		rank = 330,
		group = "Daily Quest Guides"
	},
	{
		description = "Storm Peaks (Dun Niffelem, K3)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWSP",
		rank = 331,
		group = "Daily Quest Guides"
	},
	{
		description = "Storm Peaks (Dun Niffelem, K3)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWSP",
		rank = 332,
		group = "Daily Quest Guides"
	},
	{
		description = "Icecrown (Lots of Dailies)",
		faction = "Horde",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "HDWIC",
		rank = 333,
		group = "Daily Quest Guides"
	},
	{
		description = "Icecrown (Lots of Dailies)",
		faction = "Alliance",
		era = true,
		tbc = true,
		moduleID = "Wrath",
		guideID = "ADWIC",
		rank = 334,
		group = "Daily Quest Guides"
	},
}
